# Generated by Django 4.2.7 on 2025-03-06 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma_aulas', '0002_customuser_is_active_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='link_video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
